import type { Metadata } from "next";
import { Merriweather, Kanit } from "next/font/google";
import "./globals.css";
import Provider from "@/context/Provider";
import NavbarApp from "@/app/components/navbar/NavbarApp";
import {cn} from "@/lib/utils";

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-merriweather",
});
const kanit = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-kanit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(`${merriweather.variable} ${kanit.variable}`)}>
        <Provider>
          <NavbarApp />
          {children}
        </Provider>
      </body>
    </html>
  );
}
